services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mail:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025
      - 1025:1025